### ISSUE TITLE
Could you add the repeatable check like the open lock

### ISSUE THREAD

**Issue by Rubengam3r** [rinnocenti/innocenti-loot#2]
Could it be added to the settings of the module to allow for multiple checks? This way more than one player could loot a dead NPC.

**Comment by rinnocenti** [comment]
I believe this escapes the premise of the game/module.
because the same npc doesn't have 5 armors or 5 swords.
the idea of the module is that you collect all the loot at once. not replicate for each player.

but if you find it somehow plausible, you can run the module in "debug" mode which doesn't check the number of times the same npc is looted.
